import { type EmailOtpType } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

/**
 * Verifies an email OTP link generated by the Send-Email auth hook, then
 * redirects to `next`. This is the destination the branded auth emails point
 * at (rather than Supabase's default `/auth/v1/verify`), keeping the PKCE flow
 * inside the app origin — mirroring the `/auth/callback` pattern.
 */
export async function GET(request: Request) {
  const { searchParams, origin } = new URL(request.url);
  const token_hash = searchParams.get("token_hash");
  const type = searchParams.get("type") as EmailOtpType | null;
  const next = searchParams.get("next") ?? "/";

  if (token_hash && type) {
    const supabase = await createClient();
    const { error } = await supabase.auth.verifyOtp({ type, token_hash });
    if (!error) {
      // `next` may be an absolute URL (from redirect_to) or a relative path.
      const destination = next.startsWith("http")
        ? next
        : `${origin}${next.startsWith("/") ? next : `/${next}`}`;
      return NextResponse.redirect(destination);
    }
    return NextResponse.redirect(
      `${origin}/login?error=${encodeURIComponent(error.message)}`
    );
  }

  return NextResponse.redirect(`${origin}/login?error=auth_confirm_error`);
}
