import type { VerbBlock } from "../_components/VerbBlocks";

// TEMPORARY single-page preview for `/french-verb-aller.html`.
// A faithful reconstruction of the legacy SiteSell page's content STRUCTURE
// (verbatim headings, original order, mnemonic inline, lead image + conjugation
// table in their original mid-page positions). Generated by the DOM-order
// flattener in docs/seo-migration. Once the model is signed off this moves into
// the `verb_conjugations` table as an ordered `blocks` column for all 748 pages.
export const ALLER_BLOCKS: VerbBlock[] = [
  { type: "para", html: "Easy Cheat's Way to Form the French Future Tense" },
  { type: "heading", level: 2, text: "A Top Ten French Verb" },
  {
    type: "para",
    html: "French verb <strong>ALLER</strong> is <strong>French for go</strong>, or <strong>to go</strong>. To <strong>remember</strong> this imagine: <strong>you GO down the ALLEY to ALLAY his fears.</strong>",
  },
  {
    type: "para",
    html: 'Aller is one of the <a href="https://www.200words-a-day.com/important-french-verbs.html">ten most important verbs in French</a>, and one that you should learn at an early stage in your French learning.',
  },
  { type: "heading", level: 3, text: "FRENCH SHORTCUT:" },
  {
    type: "para",
    html: '<strong>Aller</strong> provides a great way to express the future. <strong>Aller</strong> is used in spoken French as a quick way to express the future. It is the same construction as English phrases like "I am going to ~" after which you can put any verb.',
  },
  {
    type: "para",
    html: 'You can put any <strong>INFINITIVE</strong> of almost any verb after the French equivalent of <strong>"going to"</strong>, and this acts as a future tense. This is a great "cheat" for beginners, before they have mastered the future tense. (See the examples below the table).',
  },
  {
    type: "para",
    html: 'French vocabulary learning is fastest when using <a href="https://www.200words-a-day.com/learn-french.html">picture memory triggers</a>',
  },
  {
    type: "para",
    html: "Take a couple of minutes to read aloud ALL the verb conjugations of <strong>aller</strong> below -",
  },
  {
    type: "para",
    html: "by (1) <strong>ROW</strong> and by (2) <strong>COLUMN</strong> ... then check out more on this word below the verb table.",
  },
  {
    type: "image",
    src: "https://www.200words-a-day.com/images/aller.gif",
    alt: "french-verb-to-go-is-aller",
  },
  { type: "para", html: "<strong>to go: aller</strong>" },
  { type: "para", html: "Imagine <strong>you GO down the ALLEY to ALLAY his fears.</strong>" },
  { type: "conjugation" },
  { type: "heading", level: 3, text: "MORE on the FRENCH VERB ALLER" },
  { type: "para", html: "The first meaning of the French verb <strong>aller</strong> is to go:" },
  { type: "para", html: "<strong>Òu vas-tu? Je vais á la boulangerie.</strong>" },
  { type: "para", html: "Where are you going? I’m going to the bakery." },
  { type: "para", html: "It can also be used to ask about people’s health:" },
  { type: "para", html: "<strong>Comment vas-tu ? Je vais bien merci.</strong>" },
  { type: "para", html: "How are you? I’m fine thank you." },
  { type: "para", html: "<strong>Comment va ta jambe ? Elle me fait encore un peu mal.</strong>" },
  { type: "para", html: "How is your leg? It still hurts a little." },
  { type: "para", html: "Here are some other expressions using the French verb <em>aller</em>:" },
  { type: "para", html: "<strong>Cette robe te va comme un gant.</strong>" },
  { type: "para", html: "This dress fits you like a glove." },
  { type: "para", html: "<strong>Faire des va-et-vient</strong>" },
  { type: "para", html: "to go back and forth" },
  { type: "para", html: "<strong>Va-t’en!</strong>" },
  { type: "para", html: "Get away!" },
  { type: "para", html: "<strong>Allez-y!</strong>" },
  { type: "para", html: "Go ahead!" },
  { type: "para", html: "<strong>Allez, prends-le!</strong>" },
  { type: "para", html: "Come on, take it!" },
  { type: "para", html: "<strong>Les verres vont au-dessus de l’évier.</strong>" },
  { type: "para", html: "Glasses go above the sink." },
  { type: "para", html: "<strong>Allez les Bleus!</strong>" },
  { type: "para", html: "Come on France! Go France!" },
  {
    type: "para",
    html: "<strong>Les Bleus</strong> signifies the blue jerseys of the French national football and rugby teams.",
  },
  {
    type: "para",
    html: "<strong>Aller</strong> is also used as a 'future' tense, in the same way as we use the expression 'going to' in English:",
  },
  { type: "para", html: "<strong>Je vais étudier à la Sorbonne.</strong>" },
  { type: "para", html: "I am going to study at the Sorbonne (University in Paris)." },
  { type: "para", html: "<strong>Il va venir tout de suite.</strong>" },
  { type: "para", html: "He is going to come soon." },
  { type: "para", html: "<strong>On va voir.</strong>" },
  { type: "para", html: "We will see. (One will see)." },
  { type: "heading", level: 3, text: "HOW TO CONQUER FRENCH VERB CONJUGATION of ALLER" },
  { type: "para", html: "The French verb for go <strong>aller</strong> is an <strong>irregular verb</strong>." },
  {
    type: "para",
    html: "Repeating these tables aloud <strong>10 times throughout the day</strong> will better embed the patterns into your subconscious, and your long term memory.",
  },
  {
    type: "para",
    html: "Reciting aloud is a great way for you to practice your pronunciation, and helps you to memorize the conjugations.",
  },
];
