// Barrel file: re-exports both the auto-generated Supabase types and the
// hand-written convenience aliases. Keep this file as a re-export only —
// see `database-generated.ts` (auto-generated by `supabase gen types`) and
// `aliases.ts` (hand-written convenience aliases).
export * from "./database-generated";
export * from "./aliases";
